%YAML:1.0

image.width: 640
image.height: 480

## TUM fr1
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 318.6
camera.cy: 255.3

camera.d0: 0.2624
camera.d1: -0.9531
camera.d2: -0.0054
camera.d3: 0.0026
camera.d4: 1.1633

## TUM fr2
# camera.fx: 520.9
# camera.fy: 521.0
# camera.cx: 325.1
# camera.cy: 249.7

depth.scale: 5000

frame.pyramid: 5
#25
feature.cell: 10
#20
feature.detection_threshold: 15.0

tracker.min_features: 50


